// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Comment struct {
	Id        int64  `json:"id"`
	Content   string `json:"content"`
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	PostId    int64  `json:"post_id"`
	CreatedAt string `json:"created_at"`
}

type CommentListResp struct {
	Comments []Comment `json:"comments"`
	Total    int64     `json:"total"`
}

type CreateCommentReq struct {
	Content string `json:"content"`
	PostId  int64  `json:"post_id"`
}

type CreatePostReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

type Post struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type PostListResp struct {
	Posts []Post `json:"posts"`
	Total int64  `json:"total"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type UpdatePostReq struct {
	Id      int64  `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type User struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
