// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: blog.proto

package server

import (
	"context"

	"blog-system/services/blog/blog"
	"blog-system/services/blog/internal/logic"
	"blog-system/services/blog/internal/svc"
)

type BlogServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedBlogServer
}

func NewBlogServer(svcCtx *svc.ServiceContext) *BlogServer {
	return &BlogServer{
		svcCtx: svcCtx,
	}
}

func (s *BlogServer) Ping(ctx context.Context, in *blog.Request) (*blog.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
