// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: blog.proto

package server

import (
	"context"

	"blog-system/services/blog/blog"
	"blog-system/services/blog/internal/logic"
	"blog-system/services/blog/internal/svc"
)

type BlogServiceServer struct {
	svcCtx *svc.ServiceContext
	blog.UnimplementedBlogServiceServer
}

func NewBlogServiceServer(svcCtx *svc.ServiceContext) *BlogServiceServer {
	return &BlogServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *BlogServiceServer) CreatePost(ctx context.Context, in *blog.CreatePostRequest) (*blog.CreatePostResponse, error) {
	l := logic.NewCreatePostLogic(ctx, s.svcCtx)
	return l.CreatePost(in)
}

func (s *BlogServiceServer) GetPost(ctx context.Context, in *blog.GetPostRequest) (*blog.GetPostResponse, error) {
	l := logic.NewGetPostLogic(ctx, s.svcCtx)
	return l.GetPost(in)
}

func (s *BlogServiceServer) ListPosts(ctx context.Context, in *blog.ListPostsRequest) (*blog.ListPostsResponse, error) {
	l := logic.NewListPostsLogic(ctx, s.svcCtx)
	return l.ListPosts(in)
}

func (s *BlogServiceServer) UpdatePost(ctx context.Context, in *blog.UpdatePostRequest) (*blog.UpdatePostResponse, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *BlogServiceServer) DeletePost(ctx context.Context, in *blog.DeletePostRequest) (*blog.DeletePostResponse, error) {
	l := logic.NewDeletePostLogic(ctx, s.svcCtx)
	return l.DeletePost(in)
}
