// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ImageRequest struct {
	UserID uint `header:"User-ID"`
}

type ImageResponse struct {
	Url string `json:"url"`
}

type ImageShowRequest struct {
	ImageType string `path:"imageType"`
	ImageName string `path:"imageName"`
}

type ImageShowResponse struct {
}
