// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: comment.proto

package server

import (
	"context"

	"comment/internal/logic"
	"comment/internal/svc"
	"comment/types/comment"
)

type CommentServiceServer struct {
	svcCtx *svc.ServiceContext
	comment.UnimplementedCommentServiceServer
}

func NewCommentServiceServer(svcCtx *svc.ServiceContext) *CommentServiceServer {
	return &CommentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServiceServer) CreateComment(ctx context.Context, in *comment.CreateCommentRequest) (*comment.CreateCommentResponse, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

func (s *CommentServiceServer) ListComments(ctx context.Context, in *comment.ListCommentsRequest) (*comment.ListCommentsResponse, error) {
	l := logic.NewListCommentsLogic(ctx, s.svcCtx)
	return l.ListComments(in)
}
