// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: ListPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:id",
				Handler: GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:post_id/comments",
				Handler: ListCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/comments",
				Handler: CreateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/posts/:id",
				Handler: UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/posts/:id",
				Handler: DeletePostHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
