// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: blog.proto

package blogClient

import (
	"context"

	"blog-system/services/blog/blog"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = blog.Request
	Response = blog.Response

	Blog interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultBlog struct {
		cli zrpc.Client
	}
)

func NewBlog(cli zrpc.Client) Blog {
	return &defaultBlog{
		cli: cli,
	}
}

func (m *defaultBlog) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := blog.NewBlogClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
