// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user_rpc.proto

package user_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCreateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NickName       string                 `protobuf:"bytes,1,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Password       string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role           int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	Avatar         string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	OpenId         string                 `protobuf:"bytes,5,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	RegisterSource string                 `protobuf:"bytes,6,opt,name=register_source,json=registerSource,proto3" json:"register_source,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserCreateRequest) Reset() {
	*x = UserCreateRequest{}
	mi := &file_user_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRequest) ProtoMessage() {}

func (x *UserCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRequest.ProtoReflect.Descriptor instead.
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreateRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreateRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserCreateRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserCreateRequest) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *UserCreateRequest) GetRegisterSource() string {
	if x != nil {
		return x.RegisterSource
	}
	return ""
}

type UserCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateResponse) Reset() {
	*x = UserCreateResponse{}
	mi := &file_user_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateResponse) ProtoMessage() {}

func (x *UserCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateResponse.ProtoReflect.Descriptor instead.
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreateResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRequest) Reset() {
	*x = UserInfoRequest{}
	mi := &file_user_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequest) ProtoMessage() {}

func (x *UserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequest.ProtoReflect.Descriptor instead.
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfoRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 用户和用户配置的json
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_user_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NickName      string                 `protobuf:"bytes,1,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UserBaseInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBaseInfoRequest) Reset() {
	*x = UserBaseInfoRequest{}
	mi := &file_user_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBaseInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBaseInfoRequest) ProtoMessage() {}

func (x *UserBaseInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBaseInfoRequest.ProtoReflect.Descriptor instead.
func (*UserBaseInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *UserBaseInfoRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserBaseInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBaseInfoResponse) Reset() {
	*x = UserBaseInfoResponse{}
	mi := &file_user_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBaseInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBaseInfoResponse) ProtoMessage() {}

func (x *UserBaseInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBaseInfoResponse.ProtoReflect.Descriptor instead.
func (*UserBaseInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *UserBaseInfoResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserBaseInfoResponse) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserBaseInfoResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UserListInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdList    []uint32               `protobuf:"varint,1,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"` // 用户id列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListInfoRequest) Reset() {
	*x = UserListInfoRequest{}
	mi := &file_user_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListInfoRequest) ProtoMessage() {}

func (x *UserListInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListInfoRequest.ProtoReflect.Descriptor instead.
func (*UserListInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *UserListInfoRequest) GetUserIdList() []uint32 {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

type UserListInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      map[uint32]*UserInfo   `protobuf:"bytes,1,rep,name=user_info,json=userInfo,proto3" json:"user_info,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListInfoResponse) Reset() {
	*x = UserListInfoResponse{}
	mi := &file_user_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListInfoResponse) ProtoMessage() {}

func (x *UserListInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListInfoResponse.ProtoReflect.Descriptor instead.
func (*UserListInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *UserListInfoResponse) GetUserInfo() map[uint32]*UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type IsFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1         uint32                 `protobuf:"varint,1,opt,name=user1,proto3" json:"user1,omitempty"`
	User2         uint32                 `protobuf:"varint,2,opt,name=user2,proto3" json:"user2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendRequest) Reset() {
	*x = IsFriendRequest{}
	mi := &file_user_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendRequest) ProtoMessage() {}

func (x *IsFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendRequest.ProtoReflect.Descriptor instead.
func (*IsFriendRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *IsFriendRequest) GetUser1() uint32 {
	if x != nil {
		return x.User1
	}
	return 0
}

func (x *IsFriendRequest) GetUser2() uint32 {
	if x != nil {
		return x.User2
	}
	return 0
}

type IsFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFriend      bool                   `protobuf:"varint,1,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendResponse) Reset() {
	*x = IsFriendResponse{}
	mi := &file_user_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendResponse) ProtoMessage() {}

func (x *IsFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendResponse.ProtoReflect.Descriptor instead.
func (*IsFriendResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *IsFriendResponse) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

type FriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          uint32                 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListRequest) Reset() {
	*x = FriendListRequest{}
	mi := &file_user_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListRequest) ProtoMessage() {}

func (x *FriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListRequest.ProtoReflect.Descriptor instead.
func (*FriendListRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *FriendListRequest) GetUser() uint32 {
	if x != nil {
		return x.User
	}
	return 0
}

type FriendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendInfo) Reset() {
	*x = FriendInfo{}
	mi := &file_user_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfo) ProtoMessage() {}

func (x *FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfo.ProtoReflect.Descriptor instead.
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *FriendInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FriendInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *FriendInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type FriendListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendList    []*FriendInfo          `protobuf:"bytes,1,rep,name=friend_list,json=friendList,proto3" json:"friend_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListResponse) Reset() {
	*x = FriendListResponse{}
	mi := &file_user_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListResponse) ProtoMessage() {}

func (x *FriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListResponse.ProtoReflect.Descriptor instead.
func (*FriendListResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *FriendListResponse) GetFriendList() []*FriendInfo {
	if x != nil {
		return x.FriendList
	}
	return nil
}

type UserOnlineListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOnlineListRequest) Reset() {
	*x = UserOnlineListRequest{}
	mi := &file_user_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOnlineListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineListRequest) ProtoMessage() {}

func (x *UserOnlineListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineListRequest.ProtoReflect.Descriptor instead.
func (*UserOnlineListRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{14}
}

type UserOnlineListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdList    []uint32               `protobuf:"varint,1,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOnlineListResponse) Reset() {
	*x = UserOnlineListResponse{}
	mi := &file_user_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOnlineListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineListResponse) ProtoMessage() {}

func (x *UserOnlineListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineListResponse.ProtoReflect.Descriptor instead.
func (*UserOnlineListResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *UserOnlineListResponse) GetUserIdList() []uint32 {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

var File_user_rpc_proto protoreflect.FileDescriptor

const file_user_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0euser_rpc.proto\x12\buser_rpc\"\xba\x01\n" +
	"\x11UserCreateRequest\x12\x1b\n" +
	"\tnick_name\x18\x01 \x01(\tR\bnickName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x17\n" +
	"\aopen_id\x18\x05 \x01(\tR\x06openId\x12'\n" +
	"\x0fregister_source\x18\x06 \x01(\tR\x0eregisterSource\"-\n" +
	"\x12UserCreateResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"*\n" +
	"\x0fUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"&\n" +
	"\x10UserInfoResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"?\n" +
	"\bUserInfo\x12\x1b\n" +
	"\tnick_name\x18\x01 \x01(\tR\bnickName\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\".\n" +
	"\x13UserBaseInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"d\n" +
	"\x14UserBaseInfoResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tnick_name\x18\x02 \x01(\tR\bnickName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"7\n" +
	"\x13UserListInfoRequest\x12 \n" +
	"\fuser_id_list\x18\x01 \x03(\rR\n" +
	"userIdList\"\xb2\x01\n" +
	"\x14UserListInfoResponse\x12I\n" +
	"\tuser_info\x18\x01 \x03(\v2,.user_rpc.UserListInfoResponse.UserInfoEntryR\buserInfo\x1aO\n" +
	"\rUserInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.user_rpc.UserInfoR\x05value:\x028\x01\"=\n" +
	"\x0fIsFriendRequest\x12\x14\n" +
	"\x05user1\x18\x01 \x01(\rR\x05user1\x12\x14\n" +
	"\x05user2\x18\x02 \x01(\rR\x05user2\"/\n" +
	"\x10IsFriendResponse\x12\x1b\n" +
	"\tis_friend\x18\x01 \x01(\bR\bisFriend\"'\n" +
	"\x11FriendListRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\rR\x04user\"Z\n" +
	"\n" +
	"FriendInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tnick_name\x18\x02 \x01(\tR\bnickName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"K\n" +
	"\x12FriendListResponse\x125\n" +
	"\vfriend_list\x18\x01 \x03(\v2\x14.user_rpc.FriendInfoR\n" +
	"friendList\"\x17\n" +
	"\x15UserOnlineListRequest\":\n" +
	"\x16UserOnlineListResponse\x12 \n" +
	"\fuser_id_list\x18\x01 \x03(\rR\n" +
	"userIdList2\x92\x04\n" +
	"\x05Users\x12G\n" +
	"\n" +
	"UserCreate\x12\x1b.user_rpc.UserCreateRequest\x1a\x1c.user_rpc.UserCreateResponse\x12A\n" +
	"\bUserInfo\x12\x19.user_rpc.UserInfoRequest\x1a\x1a.user_rpc.UserInfoResponse\x12M\n" +
	"\fUserBaseInfo\x12\x1d.user_rpc.UserBaseInfoRequest\x1a\x1e.user_rpc.UserBaseInfoResponse\x12M\n" +
	"\fUserListInfo\x12\x1d.user_rpc.UserListInfoRequest\x1a\x1e.user_rpc.UserListInfoResponse\x12A\n" +
	"\bIsFriend\x12\x19.user_rpc.IsFriendRequest\x1a\x1a.user_rpc.IsFriendResponse\x12G\n" +
	"\n" +
	"FriendList\x12\x1b.user_rpc.FriendListRequest\x1a\x1c.user_rpc.FriendListResponse\x12S\n" +
	"\x0eUserOnlineList\x12\x1f.user_rpc.UserOnlineListRequest\x1a .user_rpc.UserOnlineListResponseB\fZ\n" +
	"./user_rpcb\x06proto3"

var (
	file_user_rpc_proto_rawDescOnce sync.Once
	file_user_rpc_proto_rawDescData []byte
)

func file_user_rpc_proto_rawDescGZIP() []byte {
	file_user_rpc_proto_rawDescOnce.Do(func() {
		file_user_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_rpc_proto_rawDesc), len(file_user_rpc_proto_rawDesc)))
	})
	return file_user_rpc_proto_rawDescData
}

var file_user_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_user_rpc_proto_goTypes = []any{
	(*UserCreateRequest)(nil),      // 0: user_rpc.UserCreateRequest
	(*UserCreateResponse)(nil),     // 1: user_rpc.UserCreateResponse
	(*UserInfoRequest)(nil),        // 2: user_rpc.UserInfoRequest
	(*UserInfoResponse)(nil),       // 3: user_rpc.UserInfoResponse
	(*UserInfo)(nil),               // 4: user_rpc.UserInfo
	(*UserBaseInfoRequest)(nil),    // 5: user_rpc.UserBaseInfoRequest
	(*UserBaseInfoResponse)(nil),   // 6: user_rpc.UserBaseInfoResponse
	(*UserListInfoRequest)(nil),    // 7: user_rpc.UserListInfoRequest
	(*UserListInfoResponse)(nil),   // 8: user_rpc.UserListInfoResponse
	(*IsFriendRequest)(nil),        // 9: user_rpc.IsFriendRequest
	(*IsFriendResponse)(nil),       // 10: user_rpc.IsFriendResponse
	(*FriendListRequest)(nil),      // 11: user_rpc.FriendListRequest
	(*FriendInfo)(nil),             // 12: user_rpc.FriendInfo
	(*FriendListResponse)(nil),     // 13: user_rpc.FriendListResponse
	(*UserOnlineListRequest)(nil),  // 14: user_rpc.UserOnlineListRequest
	(*UserOnlineListResponse)(nil), // 15: user_rpc.UserOnlineListResponse
	nil,                            // 16: user_rpc.UserListInfoResponse.UserInfoEntry
}
var file_user_rpc_proto_depIdxs = []int32{
	16, // 0: user_rpc.UserListInfoResponse.user_info:type_name -> user_rpc.UserListInfoResponse.UserInfoEntry
	12, // 1: user_rpc.FriendListResponse.friend_list:type_name -> user_rpc.FriendInfo
	4,  // 2: user_rpc.UserListInfoResponse.UserInfoEntry.value:type_name -> user_rpc.UserInfo
	0,  // 3: user_rpc.Users.UserCreate:input_type -> user_rpc.UserCreateRequest
	2,  // 4: user_rpc.Users.UserInfo:input_type -> user_rpc.UserInfoRequest
	5,  // 5: user_rpc.Users.UserBaseInfo:input_type -> user_rpc.UserBaseInfoRequest
	7,  // 6: user_rpc.Users.UserListInfo:input_type -> user_rpc.UserListInfoRequest
	9,  // 7: user_rpc.Users.IsFriend:input_type -> user_rpc.IsFriendRequest
	11, // 8: user_rpc.Users.FriendList:input_type -> user_rpc.FriendListRequest
	14, // 9: user_rpc.Users.UserOnlineList:input_type -> user_rpc.UserOnlineListRequest
	1,  // 10: user_rpc.Users.UserCreate:output_type -> user_rpc.UserCreateResponse
	3,  // 11: user_rpc.Users.UserInfo:output_type -> user_rpc.UserInfoResponse
	6,  // 12: user_rpc.Users.UserBaseInfo:output_type -> user_rpc.UserBaseInfoResponse
	8,  // 13: user_rpc.Users.UserListInfo:output_type -> user_rpc.UserListInfoResponse
	10, // 14: user_rpc.Users.IsFriend:output_type -> user_rpc.IsFriendResponse
	13, // 15: user_rpc.Users.FriendList:output_type -> user_rpc.FriendListResponse
	15, // 16: user_rpc.Users.UserOnlineList:output_type -> user_rpc.UserOnlineListResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_rpc_proto_init() }
func file_user_rpc_proto_init() {
	if File_user_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_rpc_proto_rawDesc), len(file_user_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_rpc_proto_goTypes,
		DependencyIndexes: file_user_rpc_proto_depIdxs,
		MessageInfos:      file_user_rpc_proto_msgTypes,
	}.Build()
	File_user_rpc_proto = out.File
	file_user_rpc_proto_goTypes = nil
	file_user_rpc_proto_depIdxs = nil
}
