// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postsFieldNames          = builder.RawFieldNames(&Posts{})
	postsRows                = strings.Join(postsFieldNames, ",")
	postsRowsExpectAutoSet   = strings.Join(stringx.Remove(postsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postsRowsWithPlaceHolder = strings.Join(stringx.Remove(postsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	postsModel interface {
		Insert(ctx context.Context, data *Posts) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Posts, error)
		Update(ctx context.Context, data *Posts) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPostsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Posts struct {
		Id        int64     `db:"id"`
		Title     string    `db:"title"`
		Content   string    `db:"content"`
		UserId    int64     `db:"user_id"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newPostsModel(conn sqlx.SqlConn) *defaultPostsModel {
	return &defaultPostsModel{
		conn:  conn,
		table: "`posts`",
	}
}

func (m *defaultPostsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPostsModel) FindOne(ctx context.Context, id int64) (*Posts, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postsRows, m.table)
	var resp Posts
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostsModel) Insert(ctx context.Context, data *Posts) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, postsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.UserId)
	return ret, err
}

func (m *defaultPostsModel) Update(ctx context.Context, data *Posts) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, postsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.UserId, data.Id)
	return err
}

func (m *defaultPostsModel) tableName() string {
	return m.table
}
